// Hyperion/ai-service.js

/**
 * Simulates a call to a Generative AI model.
 *
 * @param {string} prompt The prompt to send to the AI.
 * @param {object} options Optional parameters for the AI call (e.g., maxTokens, temperature).
 * @returns {Promise<string>} A promise that resolves with the AI's mock response.
 */
async function generateAiText(prompt, options = {}) {
  console.log("Mock AI Call Initiated");
  console.log("Prompt:", prompt);
  console.log("Options:", options);

  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500)); // Shorter delay for refinement

  // Mock responses based on keywords in the prompt
  let mockResponse = "This is a generic refined mock AI response.";

  // --- Existing General Mocks ( रखा ) ---
  if (prompt.toLowerCase().includes("keywords")) {
    mockResponse = "Refined AI Keyword A, Refined AI Keyword B, Refined AI Keyword C";
  } else if (prompt.toLowerCase().includes("domain")) {
    mockResponse = "computer_science"; // Example domain
  } else if (prompt.toLowerCase().includes("hypothesis type")) {
    mockResponse = "directional";
  } else if (prompt.toLowerCase().includes("hypothesis statement") && !prompt.toLowerCase().includes("refine")) { // Avoid conflict with more specific prompts
    mockResponse = "Refined AI: If [Independent Variable] is altered, then [Dependent Variable] will show a significant [direction] change, measured by [metric].";
  } else if (prompt.toLowerCase().includes("null hypothesis")) {
    mockResponse = "There is no significant relationship between X and Y (generated by AI).";
  } else if (prompt.toLowerCase().includes("alternative hypothesis")) {
    mockResponse = "There is a significant relationship between X and Y (generated by AI).";
  } else if (prompt.toLowerCase().includes("justification")) {
    mockResponse = "This hypothesis is based on the preliminary data suggesting a correlation (generated by AI).";
  } else if (prompt.toLowerCase().includes("python code for experiment")) {
    mockResponse = `
# AI Generated Python Code
import numpy as np
# import matplotlib.pyplot as plt # Usually not executable in simple env

# Simulate some data
x = np.linspace(0, 10, 100)
y = 2 * x + 1 + np.random.normal(0, 1, 100) # y = mx + c + noise

# Simple linear regression
slope, intercept = np.polyfit(x, y, 1)
print(f"Generated slope: {slope:.2f}")
print(f"Generated intercept: {intercept:.2f}")
# Calculate R-squared (simplified for mock)
y_pred = slope * x + intercept
ss_res = np.sum((y - y_pred)**2)
ss_tot = np.sum((y - np.mean(y))**2)
r_squared = 1 - (ss_res / ss_tot)
print(f"R-squared: {r_squared:.4f}")

print("Mock experiment simulation complete. Results: Slope, Intercept, and R-squared calculated.")
`;
  }
  // --- Peer Review Mocks (Step 9) ---
  else if (prompt.toLowerCase().includes("critically assess the scientific merit")) {
    mockResponse = "8.5";
  } else if (prompt.toLowerCase().includes("critically assess the methodology")) {
    mockResponse = "7.5";
  } else if (prompt.toLowerCase().includes("critically assess the data analysis")) {
    mockResponse = "8.0";
  } else if (prompt.toLowerCase().includes("critically assess the conclusion validity")) {
    mockResponse = "7.0";
  } else if (prompt.toLowerCase().includes("key strengths of this research")) {
    mockResponse = "Refined AI: The research question is clearly defined, and the hypothesis is testable. The chosen methodology, though simulated, is appropriate for the question.";
  } else if (prompt.toLowerCase().includes("key areas for improvement")) {
    mockResponse = "Refined AI: The primary weakness is the reliance on simulated data without real-world validation. The statistical analysis could be more robust, detailing tests used.";
  } else if (prompt.toLowerCase().includes("specific, actionable recommendations")) {
    mockResponse = `* Validate findings with a small real-world dataset.
* Explicitly state the statistical tests used during the analysis phase.
* Discuss the impact of simulation limitations more thoroughly in the paper.`;
  } else if (prompt.toLowerCase().includes("draft a polite and constructive response")) {
    mockResponse = "Refined AI Draft Response: We thank the reviewers for their insightful feedback. We acknowledge the points regarding real-world validation and will incorporate a more detailed discussion of statistical methods and simulation limitations in our revisions.";
  } else if (prompt.toLowerCase().includes("list specific revisions the researcher plans")) {
    mockResponse = `Refined AI Planned Revisions:
1. Add a paragraph to the Discussion section addressing the limitations of using simulated data.
2. Specify the exact statistical tests (e.g., regression analysis) in the Methodology and Results sections.
3. Include a point in Future Work about real-world data validation.`;
  }
  // --- Conclusion Status (Step 8) ---
  else if (prompt.toLowerCase().includes("does the evidence support, refute, or is it inconclusive")) {
    mockResponse = "Supports Hypothesis";
  }
  // --- Refined/New Mocks for Steps 7, 8, 10 ---
  else if (prompt.toLowerCase().includes("provide a concise interpretation of these results")) { // Step 7 - aiDataInterpretation
    mockResponse = "Refined AI Interpretation: The simulated experiment output (e.g., R-squared: 0.9982 from python script) indicates a strong positive correlation between the defined independent and dependent variables, which is consistent with the formulated hypothesis: '[Hypothesis Statement Placeholder]'. The Python code structure appears suitable for this type of simulation. No immediate errors are apparent from the output, suggesting the mock run was successful as per its design and parameters.";
  } else if (prompt.toLowerCase().includes("write a concise summary of the main conclusion")) { // Step 8 - conclusionSummary
    mockResponse = "Refined AI Conclusion Summary: Based on the AI-driven data interpretation which indicates strong support for the hypothesis ('[Hypothesis Statement Placeholder]'), this study concludes that a significant positive relationship exists between the key variables. The quantitative measures obtained from the simulation (e.g., R-squared of 0.9982) underscore a high degree of correlation as defined by the experimental parameters.";
  }
  // --- Paper Section Mocks (Step 10) ---
  else if (prompt.toLowerCase().includes("write a structured academic abstract")) { // Step 10 - Abstract
    mockResponse = `Refined AI Abstract:
Background: Understanding [Research Domain Placeholder, e.g., chemical kinetics] is essential for [broader impact, e.g., optimizing industrial processes]. Current literature points to [brief gap or context].
Objective: This study aimed to investigate [Research Question Placeholder] and test the hypothesis that [Hypothesis Statement Placeholder].
Methods: A [Experiment Type Placeholder, e.g., controlled simulation] was conducted. The primary independent variable was [Independent Variable Placeholder], and the dependent variable was [Dependent Variable Placeholder]. Data was generated using a Python script and analyzed via [Statistical Test Placeholder, e.g., regression analysis].
Results: The simulation yielded [Key Result from experimentRunOutput or aiDataInterpretation, e.g., a strong positive correlation with R-squared = 0.9982]. This indicates that as [Independent Variable] increases, [Dependent Variable] also increases significantly under the test conditions.
Conclusion: The findings provide strong support for the stated hypothesis. This simulated study highlights the potential relationship and sets a basis for future empirical validation.`;
  } else if (prompt.toLowerCase().includes("write the introduction section")) { // Step 10 - Introduction
    mockResponse = `Refined AI Introduction:
The study of [Research Domain Placeholder] forms a critical component of [broader field]. Specifically, understanding [Research Question Placeholder] has significant implications for [application or importance]. Previous research by [Mock Author, 202X] has indicated [related finding], but the specific relationship defined by our hypothesis, "[Hypothesis Statement Placeholder]," warrants further investigation within a controlled (simulated) environment. This paper details such an investigation, aiming to provide quantitative insights into this relationship. The keywords guiding this research include: [Keywords Placeholder].`;
  } else if (prompt.toLowerCase().includes("describe the methodology section")) { // Step 10 - Methodology
    mockResponse = `Refined AI Methodology:
This study employed a [Experiment Type Placeholder, e.g., simulated controlled experiment] to investigate the relationship between [Independent Variable Placeholder] (independent variable) and [Dependent Variable Placeholder] (dependent variable). The following control variables were considered: [Control Variable 1 Placeholder], [Control Variable 2 Placeholder].
The experimental procedure was as follows: [Procedure Summary Placeholder, e.g., data points were generated across a range of IV values and DV was recorded]. A total of [Sample Size Placeholder] trials/data points were simulated.
Data generation and initial analysis were performed using a Python script incorporating the 'numpy' library for numerical operations. The core logic involved [brief description of Python script's function, e.g., applying a formula y = mx + c + noise].
Statistical analysis, including [Statistical Test Placeholder, e.g., linear regression], was performed on the generated data to determine the strength and nature of the relationship.`;
  } else if (prompt.toLowerCase().includes("present the key results")) { // Step 10 - Results
    mockResponse = `Refined AI Results:
The simulation of the experiment yielded data indicating a [e.g., strong positive] relationship between [Independent Variable Placeholder] and [Dependent Variable Placeholder]. Analysis of the simulated data, using [Statistical Test Placeholder, e.g., linear regression], produced a coefficient of determination (R-squared) of [Value from experimentRunOutput, e.g., 0.9982].
The AI-driven interpretation of this data ([AI Data Interpretation Placeholder]) confirmed that this result strongly supports the initial hypothesis. Visualizations, such as a [Chart Type Placeholder, e.g., scatter plot with trendline], further illustrated this relationship (details of chart would be in a figure, not reproduced in text here).
The primary outcome from the Python script execution was: [Key numerical result from experimentRunOutput, e.g., Slope: X, Intercept: Y, R-squared: Z]. No errors were reported during the simulated execution.`;
  } else if (prompt.toLowerCase().includes("write the discussion section")) { // Step 10 - Discussion
    mockResponse = `Refined AI Discussion:
The results obtained from this simulated study provide strong support for the hypothesis that [Hypothesis Statement Placeholder]. The quantitative findings, particularly the [Key Result from experimentRunOutput, e.g., R-squared value of 0.9982], are consistent with the AI-generated data interpretation which suggested a [Conclusion Status Placeholder, e.g., strong positive correlation].
These findings align with general theoretical expectations within the domain of [Research Domain Placeholder]. For instance, the observed trend is comparable to [mock comparison to a known principle or similar fictional study].
However, it is crucial to acknowledge the limitations inherent in this study, as detailed previously ([Limitations Placeholder, e.g., reliance on simulation, specific parameter range]). The use of simulated data, while useful for isolating variables, does not capture the full complexity of real-world conditions. Therefore, the direct applicability of these specific quantitative results to empirical settings should be approached with caution.
Future research, as outlined ([Future Directions Placeholder, e.g., empirical validation, wider parameter testing]), should aim to address these limitations and build upon the foundational insights gained from this simulation.`;
  } else if (prompt.toLowerCase().includes("write the overall conclusion section")) { // Step 10 - Conclusion
    mockResponse = `Refined AI Conclusion:
This study investigated the relationship between [Independent Variable Placeholder] and [Dependent Variable Placeholder] through a simulated experiment. Based on the analysis of the generated data, which yielded [Key Result from experimentRunOutput/aiDataInterpretation], it is concluded that the hypothesis ([Hypothesis Statement Placeholder]) is [Conclusion Status Placeholder, e.g., strongly supported].
The key pieces of evidence supporting this conclusion include [Evidence Support Placeholder, e.g., the statistical significance of the findings and the visual trend in data]. While the study has limitations, primarily [Key Limitation Placeholder, e.g., its simulated nature], it provides valuable preliminary insights.
Future work should focus on [Key Future Direction Placeholder, e.g., validating these results with empirical data]. Overall, this research contributes to a better understanding of [Research Question Placeholder] within a controlled, simulated context.`;
  } else if (prompt.toLowerCase().includes("mock academic references")) { // Step 10 - References
    mockResponse = `1. Mockington, A. B., & Simulato, C. D. (2023). Advances in Simulated Experimental Design. *Journal of Hypothetical Studies*, 15(2), 45-67.
2. Theorist, E. F., & Model, G. H. (2022). Computational Approaches in [Research Domain Placeholder]. *Digital Research Press.*
3. Pyper, I. J. (2024). Numpy and Scipy in Modern Research: A Practical Guide. *Pythonic Publishing House.*`;
  } else if (prompt.toLowerCase().includes("summarize key peer review feedback")) { // Step 10 - Appendix
    mockResponse = `Refined AI Appendix:
**Peer Review Summary:**
The AI-generated peer review highlighted the following:
Strengths: [Strengths from aiPeerReviewData Placeholder]
Areas for Improvement: [Improvements from aiPeerReviewData Placeholder]
Specific Recommendations: [Recommendations from aiPeerReviewData Placeholder]

**Researcher's Response:**
[Researcher's Response to Review Placeholder]

**Planned Revisions:**
[Planned Revisions Based on Review Placeholder]

**Core Python Simulation Code:**
\`\`\`python
${localStorage.getItem('actualGeneratedPythonCode') || "# Python code not found in localStorage."}
\`\`\`
`;
  }

  console.log("Refined Mock AI Response:", mockResponse);
  return mockResponse;
}

// Example of how this might be used (optional, for testing)
// (async () => {
//   const keywordsPrompt = "Generate keywords for a research paper titled 'The Future of AI in Education' with research question 'How will AI transform teaching methods?'";
//   const keywords = await generateAiText(keywordsPrompt);
//   console.log("Received keywords:", keywords);

//   const domainPrompt = "Determine the research domain for a paper titled 'The Future of AI in Education'.";
//   const domain = await generateAiText(domainPrompt);
//   console.log("Received domain:", domain);
// })();
